import { Gift } from './types';

export const EVENT = {
  babyName: 'Olivia Isabelle',
  parentsName: 'Gabriela',
  date: '05 de Julio, 4:00 PM',
  location:{
    name: 'Calle Erik Leonard Ekman #28, Residencial Janice, Viejo Arroyo Hondo',
    addressLink: 'https://maps.app.goo.gl/2hihT5bQ3ksASg3W7',
  },
  bebemundoRegistryUrl:
    'https://babyshower.bebemundo.com.do/baby/verproductos.asp?numero=72661',
};

const REGISTRY_URL = 'https://babyshower.bebemundo.com.do/baby/verproductos.asp?numero=72661';

// Lista de regalos del registro Bebemundo #72661 (Gabriela & Jeremias).
export const INITIAL_GIFTS: Gift[] = [
  {
    id: 'escurridor-biberones-dbrow',
    name: 'Escurridor para Biberones DBROW',
    description: 'Escurridor para biberones.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Accesorios Biberón',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1870,
  },
  {
    id: 'aspirador-nasal-acute',
    name: 'Aspirador Nasal Eléctrico ACUTE',
    description: 'Aspirador nasal eléctrico.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Accesorios Cuidado',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 2550,
  },
  {
    id: 'protector-corral-elite',
    name: 'Protector Soft Blanco Corral ELITE',
    description: 'Protector suave para corral.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Accesorios Cama',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 895,
  },
  {
    id: 'biberones-natural-avent',
    name: 'Set 3 Biberones Natural AVENT',
    description: 'Set de 3 biberones tetina natural.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Biberones',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 2100,
  },
  {
    id: 'body-paq2-gerber-nina',
    name: 'Body Paquete 2 GERBER (0M–9M)',
    description: 'Pack de 2 bodys para bebé niña.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Body Bebe Niña',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 995,
  },
  {
    id: 'body-4pzas-gerber-interior',
    name: 'Body 4 Piezas GERBER (6M–9M)',
    description: 'Pack de 4 bodys interiores.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Body Interior',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 995,
  },
  {
    id: 'shampoo-johnsons-baby',
    name: "Shampoo Original JOHNSON'S BABY",
    description: 'Shampoo original sin lágrimas.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Cuidado Capilar',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
    price: 669.95,
  },
  {
    id: 'crema-desitin',
    name: 'Crema DESITIN',
    description: 'Crema protectora para el pañal.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Cuidado Corporal',
    store: 'bebemundo',
    totalQuantity: 4,
    availableQuantity: 4,
    price: 844.95,
  },
  {
    id: 'jabon-liquido-dove-baby',
    name: 'Jabón Líquido DOVE BABY',
    description: 'Jabón líquido suave para bebé.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Cuidado Corporal',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 419.95,
  },
  {
    id: 'locion-dove-baby',
    name: 'Loción DOVE BABY',
    description: 'Loción hidratante para bebé.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Cuidado Corporal',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
    price: 409.95,
  },
  {
    id: 'crema-liquida-johnsons',
    name: "Crema Líquida JOHNSON'S BABY",
    description: 'Crema líquida hidratante.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Cuidado Corporal',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
    price: 534.95,
  },
  {
    id: 'panales-pampers-baby-dry-s2',
    name: 'Pampers Baby Dry S2',
    description: 'Pañales etapa 2, máxima absorción.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Pañales',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
    price: 3039.95,
  },
  {
    id: 'panitos-huggies-simply-clean',
    name: 'Huggies Simply Clean',
    description: 'Pañitos húmedos sin fragancia.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Pañitos',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
    price: 734.95,
  },
  {
    id: 'detergente-dreft-newborn',
    name: 'Dreft Newborn',
    description: 'Detergente para ropa de recién nacido.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Detergente',
    store: 'bebemundo',
    totalQuantity: 4,
    availableQuantity: 4,
    price: 779.95,
  },
  {
    id: 'coche-kole-ts-green-born',
    name: 'Coche KOLE TS GREEN + Pañalera BORN',
    description: 'Coche con pañalera incluida.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Coches',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 12495,
  },
  {
    id: 'conjunto-carter-6m',
    name: "Conjunto CARTER'S (6M)",
    description: 'Conjunto para bebé niña talla 6 meses.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Conjunto Bebe Niña',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1395,
    size: '6M',
  },
  {
    id: 'conjunto-gerber-3m-9m',
    name: 'Conjunto GERBER (3M–9M)',
    description: 'Conjunto para bebé niña talla 3 a 9 meses.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Conjunto Bebe Niña',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1295,
    size: '3M–9M',
  },
  {
    id: 'conjunto-mayor-6m-24m',
    name: 'Conjunto MAYOR (6M–24M)',
    description: 'Conjunto para bebé niña talla 6 a 24 meses.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Conjunto Bebe Niña',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 3345,
    size: '6M–24M',
  },
  {
    id: 'body-paq3-gerber-enterizo',
    name: 'Body Paquete 3 GERBER',
    description: 'Pack de 3 bodys enterizos.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Enterizo',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 995,
  },
  {
    id: 'esterilizador-electrico-born',
    name: 'Esterilizador Eléctrico BORN',
    description: 'Esterilizador eléctrico para biberones.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Esterilizador',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 3795,
  },
  {
    id: 'frazada-gerber',
    name: 'Frazada GERBER',
    description: 'Frazada suave para bebé.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Frazada',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1195,
  },
  {
    id: 'hamper-blanco-nazre',
    name: 'Hamper Blanco NAZRE',
    description: 'Canasto para ropa sucia.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Hampers',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1550,
  },
  {
    id: 'bolsas-leche-materna-born',
    name: 'Bolsas Leche Materna BORN',
    description: 'Bolsas para almacenar leche materna.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
    price: 475,
  },
  {
    id: 'extractor-manual-mede-harmony',
    name: 'Extractor Manual MEDE HARMONY',
    description: 'Extractor manual cómodo y eficaz.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 3450,
  },
  {
    id: 'set-cornetas-mede-fit-flex',
    name: 'Set Cornetas MEDE FIT FLEX',
    description: 'Set de cornetas para extractor Medela.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1395,
  },
  {
    id: 'almohadillas-absorbentes-avent',
    name: 'Almohadillas Absorbentes AVENT',
    description: 'Almohadillas de lactancia desechables.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Madres',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
    price: 1050,
  },
  {
    id: 'almohada-lactancia-boppy',
    name: 'Almohada Lactancia BOPPY',
    description: 'Almohada de apoyo para lactancia.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Madres',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 3895,
  },
  {
    id: 'comoda-4-gavetas-multm',
    name: 'Cómoda 4 Gavetas MULTM',
    description: 'Cómoda organizadora de 4 gavetas.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Muebles',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 7395,
  },
  {
    id: 'toalla-capucha-2piezas',
    name: 'Toalla con Capucha (2 Piezas)',
    description: 'Set de 2 toallas con capucha para bebé.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Toalla Grande',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    price: 1995,
  },
  {
    id: 'toallitas-paq6-gerber',
    name: 'Toallitas Paquete 6 GERBER',
    description: 'Pack de 6 toallitas de tela para bebé.',
    link: REGISTRY_URL,
    imageUrl: '',
    category: 'Toalla Pequeña',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
    price: 795,
  },
];
