import { Gift } from './types';

export const EVENT = {
  babyName: 'Olivia',
  parentsName: 'Gabriela',
  date: 'Agosto 2026',
  location: 'Doral, FL',
  amazonRegistryUrl:
    'https://www.amazon.com/baby-reg/gabriela-gonzalez-agosto-2026-doral/196GFG7UVIL9E',
};

// Initial gift list — used to seed the `gifts` collection in Firestore.
// All quantities come from `public/INSUMOS/LISTA LINKS BABY SHOWER.pdf`.
export const INITIAL_GIFTS: Gift[] = [
  {
    id: 'panales-baby-dry-s2',
    name: 'Pañales Baby-Dry Etapa 2',
    description: 'Pampers Baby-Dry, paquete de 112 unidades.',
    link: 'https://bebemundo.com.do/pa-ales-etapa-2-pampers-baby-dry-112-und-paq-2151942.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2151942.jpg',
    category: 'Pañales',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
  },
  {
    id: 'toallas-huggies-192',
    name: 'Toallas Húmedas Huggies Simply Clean',
    description: '192 unidades, sin fragancia.',
    link: 'https://bebemundo.com.do/toallas-humedas-huggies-simply-clean-192-unidades-2121455.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2121455.jpg',
    category: 'Higiene',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
  },
  {
    id: 'unguento-desitin',
    name: 'Ungüento Original Desitin 2 Onz',
    description: 'Crema protectora para bebés.',
    link: 'https://bebemundo.com.do/unguento-original-para-bebes-desitin-2-onz-2043322.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/0/2043322.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
  },
  {
    id: 'crema-johnsons-400',
    name: "Crema Líquida Johnson's Baby 400 Ml",
    description: 'Hidratación suave para la piel del bebé.',
    link: 'https://bebemundo.com.do/crema-liquida-original-johnson-s-baby-400-ml-2062492.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/0/2062492.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
  },
  {
    id: 'gel-bano-dove-13',
    name: 'Gel de Baño Hidratante Dove Baby 13 Onz',
    description: 'Limpieza suave e hipoalergénica.',
    link: 'https://bebemundo.com.do/gel-de-ba-o-hidratante-dove-baby-13-onz-2198675.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2198675.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'locion-dove-13',
    name: 'Loción Hidratante Dove Baby 13 Onz',
    description: 'Hidratación post-baño.',
    link: 'https://bebemundo.com.do/locion-hidratante-dove-baby-13-onz-2198674.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2198674.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'gel-bano-dove-noche',
    name: 'Gel de Baño Calmante Noche Dove Baby 13 Onz',
    description: 'Fórmula con manzanilla para la noche.',
    link: 'https://bebemundo.com.do/gel-de-ba-o-calmante-para-la-noche-dove-baby-13-onz-2202028.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2202028.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'locion-dove-noche',
    name: 'Loción Calmante Noche Dove Baby 13 Onz',
    description: 'Para una noche tranquila.',
    link: 'https://bebemundo.com.do/locion-calmante-para-la-noche-dove-baby-13-onz-2202027.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2202027.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'shampoo-johnsons-750',
    name: "Shampoo Original Johnson's Baby 750 Ml",
    description: 'Clásico sin lágrimas.',
    link: 'https://bebemundo.com.do/shampoo-original-johnson-s-baby-750-ml-2202871.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2202871.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'caja-organizadora-sidney',
    name: 'Caja Organizadora con División Sidney Trend',
    description: 'Ideal para mantener todo a la mano.',
    link: 'https://bebemundo.com.do/caja-organizadora-con-division-sidney-trend-4182925.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4182925.jpg',
    category: 'Organización',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'banera-moby-smart',
    name: 'Bañera Moby Smart Sling Blanca',
    description: 'Cómoda y segura, con hamaca incluida.',
    link: 'https://bebemundo.com.do/ba-era-moby-smart-sling-blanca-4180916.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4180916.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'coche-muze-lx',
    name: 'Coche con Portabebé Muze LX Juva Joie',
    description: 'Sistema de viaje completo.',
    link: 'https://bebemundo.com.do/coche-con-portabebe-muze-lx-juva-joie-4167496.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4167496.jpg',
    category: 'Viaje',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'canguro-myra-gris',
    name: 'Canguro Myra Malla Gris',
    description: 'Portabebé transpirable.',
    link: 'https://bebemundo.com.do/canguro-myra-malla-gris-4191502.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4191502.jpg',
    category: 'Viaje',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'cuna-amore-blanca',
    name: 'Cuna Convertible Amore Blanca',
    description: 'Crece con el bebé.',
    link: 'https://bebemundo.com.do/cuna-convertible-amore-blanca-4188922.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4188922.jpg',
    category: 'Mobiliario',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'silla-mimzy-snacker',
    name: 'Silla para Alimentar Mimzy Snacker',
    description: 'Silla alta plegable.',
    link: 'https://bebemundo.com.do/silla-para-alimentar-mimzy-snacker-4186281.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4186281.jpg',
    category: 'Mobiliario',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'perchas-eleki-rosadas',
    name: 'Perchas Eleki 12 Piezas Rosadas',
    description: 'Para la ropita más linda.',
    link: 'https://bebemundo.com.do/perchas-eleki-12-piezas-rosadas-4155618.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4155618.jpg',
    category: 'Organización',
    store: 'bebemundo',
    totalQuantity: 10,
    availableQuantity: 10,
  },
  {
    id: 'hamper-nazaret',
    name: 'Nazaret Hamper Blanco',
    description: 'Canasto para ropa sucia.',
    link: 'https://bebemundo.com.do/nazaret-hamper-blanco-4095286.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/0/4095286.jpg',
    category: 'Organización',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'detergente-dreft-46',
    name: 'Detergente Dreft Recién Nacido 46 Onz',
    description: 'Para ropa delicada de bebé.',
    link: 'https://bebemundo.com.do/detergente-para-ropa-de-recien-nacido-dreft-46-onz-2216165.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2216165.jpg',
    category: 'Higiene',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
  },
  {
    id: 'biberones-dr-browns-rosa',
    name: 'Biberones Options Dr. Browns Rosado 5 Pzas',
    description: 'Set rosado anti-cólicos.',
    link: 'https://bebemundo.com.do/biberones-options-dr-browns-rosado-5-piezas-4188393.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4188393.jpg',
    category: 'Alimentación',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'biberones-avent-4oz',
    name: 'Avent Set 2 Biberones Natural 4 Oz',
    description: 'Tetina ultra suave.',
    link: 'https://bebemundo.com.do/avent-set-2-biberones-natural-4-oz-4112457.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4112457.jpg',
    category: 'Alimentación',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'esterilizador-avent',
    name: 'Avent Esterilizador Eléctrico Advanced',
    description: 'Esteriliza en pocos minutos.',
    link: 'https://bebemundo.com.do/avent-esterilizador-electrico-advanced-4165031.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4165031.jpg',
    category: 'Alimentación',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'extractor-harmony-medela',
    name: 'Extractor Manual Harmony Medela',
    description: 'Extractor manual cómodo y eficaz.',
    link: 'https://bebemundo.com.do/extractor-harmony-4104368.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4104368.jpg',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'extractor-bellababy',
    name: 'Bellababy Extractor Doble Eléctrico',
    description: 'Extractor doble eléctrico portátil.',
    link: 'https://bebemundo.com.do/extractor-doble-electrico-4179441.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4179441.jpg',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'almohada-lactancia-clay',
    name: 'Almohada para Lactancia Clay Gold Suns',
    description: 'Soporte cómodo para lactar.',
    link: 'https://bebemundo.com.do/almohada-para-lactancia-clay-gold-suns-4189050.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4189050.jpg',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'body-blanco-carters-5',
    name: "Body Blanco 5 Pzas Carter's",
    description: 'Set de bodys blancos clásicos.',
    link: 'https://bebemundo.com.do/body-blanco-5-pzas-carter-s-7396371.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/7/3/7396371.jpg',
    category: 'Ropa',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    size: '3 o 6 meses',
  },
  {
    id: 'set-bodys-manga-larga',
    name: 'Set 4 Bodys Manga Larga',
    description: 'Bodys blancos manga larga.',
    link: 'https://bebemundo.com.do/set-4-bodys-manga-larga-7396384.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/7/3/7396384.jpg',
    category: 'Ropa',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    size: '3 o 6 meses',
  },
  {
    id: 'enterizo-flores-carters',
    name: "Enterizo Flores Carter's",
    description: 'Set de 4 enterizos de flores.',
    link: 'https://bebemundo.com.do/enterizo-flores-carter-s-7379895.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/7/3/7379895.jpg',
    category: 'Ropa',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    size: '3 o 6 meses',
  },
];
