import { Gift } from './types';

export const EVENT = {
  babyName: 'Olivia',
  parentsName: 'Gabriela',
  date: 'Agosto 2026',
  location: 'Doral, FL',
  amazonRegistryUrl:
    'https://www.amazon.com/baby-reg/gabriela-gonzalez-agosto-2026-doral/196GFG7UVIL9E',
};

// Initial gift list — used to seed the `gifts` collection in Firestore.
// All quantities come from `public/INSUMOS/LISTA LINKS BABY SHOWER.pdf`.
export const INITIAL_GIFTS: Gift[] = [
  {
    id: 'panales-baby-dry-s2',
    name: 'Pañales Baby-Dry Etapa 2',
    description: 'Pampers Baby-Dry, paquete de 112 unidades.',
    link: 'https://bebemundo.com.do/pa-ales-etapa-2-pampers-baby-dry-112-und-paq-2151942.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2151942.jpg',
    category: 'Pañales',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
  },
  {
    id: 'toallas-huggies-192',
    name: 'Toallas Húmedas Huggies Simply Clean',
    description: '192 unidades, sin fragancia.',
    link: 'https://bebemundo.com.do/toallas-humedas-huggies-simply-clean-192-unidades-2121455.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2121455.jpg',
    category: 'Higiene',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
  },
  {
    id: 'unguento-desitin',
    name: 'Ungüento Original Desitin 2 Onz',
    description: 'Crema protectora para bebés.',
    link: 'https://bebemundo.com.do/unguento-original-para-bebes-desitin-2-onz-2043322.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/0/2043322.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
  },
  {
    id: 'crema-johnsons-400',
    name: "Crema Líquida Johnson's Baby 400 Ml",
    description: 'Hidratación suave para la piel del bebé.',
    link: 'https://bebemundo.com.do/crema-liquida-original-johnson-s-baby-400-ml-2062492.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/0/2062492.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 2,
    availableQuantity: 2,
  },
  {
    id: 'gel-bano-dove-13',
    name: 'Gel de Baño Hidratante Dove Baby 13 Onz',
    description: 'Limpieza suave e hipoalergénica.',
    link: 'https://bebemundo.com.do/gel-de-ba-o-hidratante-dove-baby-13-onz-2198675.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2198675.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'locion-dove-13',
    name: 'Loción Hidratante Dove Baby 13 Onz',
    description: 'Hidratación post-baño.',
    link: 'https://bebemundo.com.do/locion-hidratante-dove-baby-13-onz-2198674.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/1/2198674.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'gel-bano-dove-noche',
    name: 'Gel de Baño Calmante Noche Dove Baby 13 Onz',
    description: 'Fórmula con manzanilla para la noche.',
    link: 'https://bebemundo.com.do/gel-de-ba-o-calmante-para-la-noche-dove-baby-13-onz-2202028.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2202028.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'locion-dove-noche',
    name: 'Loción Calmante Noche Dove Baby 13 Onz',
    description: 'Para una noche tranquila.',
    link: 'https://bebemundo.com.do/locion-calmante-para-la-noche-dove-baby-13-onz-2202027.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2202027.jpg',
    category: 'Cuidado',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'shampoo-johnsons-750',
    name: "Shampoo Original Johnson's Baby 750 Ml",
    description: 'Clásico sin lágrimas.',
    link: 'https://bebemundo.com.do/shampoo-original-johnson-s-baby-750-ml-2202871.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2202871.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'caja-organizadora-sidney',
    name: 'Caja Organizadora con División Sidney Trend',
    description: 'Ideal para mantener todo a la mano.',
    link: 'https://bebemundo.com.do/caja-organizadora-con-division-sidney-trend-4182925.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4182925.jpg',
    category: 'Organización',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'banera-moby-smart',
    name: 'Bañera Moby Smart Sling Blanca',
    description: 'Cómoda y segura, con hamaca incluida.',
    link: 'https://bebemundo.com.do/ba-era-moby-smart-sling-blanca-4180916.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4180916.jpg',
    category: 'Baño',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'coche-muze-lx',
    name: 'Coche con Portabebé Muze LX Juva Joie',
    description: 'Sistema de viaje completo.',
    link: 'https://bebemundo.com.do/coche-con-portabebe-muze-lx-juva-joie-4167496.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4167496.jpg',
    category: 'Viaje',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'canguro-myra-gris',
    name: 'Canguro Myra Malla Gris',
    description: 'Portabebé transpirable.',
    link: 'https://bebemundo.com.do/canguro-myra-malla-gris-4191502.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4191502.jpg',
    category: 'Viaje',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'cuna-amore-blanca',
    name: 'Cuna Convertible Amore Blanca',
    description: 'Crece con el bebé.',
    link: 'https://bebemundo.com.do/cuna-convertible-amore-blanca-4188922.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4188922.jpg',
    category: 'Mobiliario',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'silla-mimzy-snacker',
    name: 'Silla para Alimentar Mimzy Snacker',
    description: 'Silla alta plegable.',
    link: 'https://bebemundo.com.do/silla-para-alimentar-mimzy-snacker-4186281.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4186281.jpg',
    category: 'Mobiliario',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'perchas-eleki-rosadas',
    name: 'Perchas Eleki 12 Piezas Rosadas',
    description: 'Para la ropita más linda.',
    link: 'https://bebemundo.com.do/perchas-eleki-12-piezas-rosadas-4155618.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4155618.jpg',
    category: 'Organización',
    store: 'bebemundo',
    totalQuantity: 10,
    availableQuantity: 10,
  },
  {
    id: 'hamper-nazaret',
    name: 'Nazaret Hamper Blanco',
    description: 'Canasto para ropa sucia.',
    link: 'https://bebemundo.com.do/nazaret-hamper-blanco-4095286.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/0/4095286.jpg',
    category: 'Organización',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'detergente-dreft-46',
    name: 'Detergente Dreft Recién Nacido 46 Onz',
    description: 'Para ropa delicada de bebé.',
    link: 'https://bebemundo.com.do/detergente-para-ropa-de-recien-nacido-dreft-46-onz-2216165.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/2/2/2216165.jpg',
    category: 'Higiene',
    store: 'bebemundo',
    totalQuantity: 3,
    availableQuantity: 3,
  },
  {
    id: 'biberones-dr-browns-rosa',
    name: 'Biberones Options Dr. Browns Rosado 5 Pzas',
    description: 'Set rosado anti-cólicos.',
    link: 'https://bebemundo.com.do/biberones-options-dr-browns-rosado-5-piezas-4188393.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4188393.jpg',
    category: 'Alimentación',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'biberones-avent-4oz',
    name: 'Avent Set 2 Biberones Natural 4 Oz',
    description: 'Tetina ultra suave.',
    link: 'https://bebemundo.com.do/avent-set-2-biberones-natural-4-oz-4112457.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4112457.jpg',
    category: 'Alimentación',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'esterilizador-avent',
    name: 'Avent Esterilizador Eléctrico Advanced',
    description: 'Esteriliza en pocos minutos.',
    link: 'https://bebemundo.com.do/avent-esterilizador-electrico-advanced-4165031.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4165031.jpg',
    category: 'Alimentación',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'extractor-harmony-medela',
    name: 'Extractor Manual Harmony Medela',
    description: 'Extractor manual cómodo y eficaz.',
    link: 'https://bebemundo.com.do/extractor-harmony-4104368.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4104368.jpg',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'extractor-bellababy',
    name: 'Bellababy Extractor Doble Eléctrico',
    description: 'Extractor doble eléctrico portátil.',
    link: 'https://bebemundo.com.do/extractor-doble-electrico-4179441.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4179441.jpg',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'almohada-lactancia-clay',
    name: 'Almohada para Lactancia Clay Gold Suns',
    description: 'Soporte cómodo para lactar.',
    link: 'https://bebemundo.com.do/almohada-para-lactancia-clay-gold-suns-4189050.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/4/1/4189050.jpg',
    category: 'Lactancia',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'body-blanco-carters-5',
    name: "Body Blanco 5 Pzas Carter's",
    description: 'Set de bodys blancos clásicos.',
    link: 'https://bebemundo.com.do/body-blanco-5-pzas-carter-s-7396371.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/7/3/7396371.jpg',
    category: 'Ropa',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    size: '3 o 6 meses',
  },
  {
    id: 'set-bodys-manga-larga',
    name: 'Set 4 Bodys Manga Larga',
    description: 'Bodys blancos manga larga.',
    link: 'https://bebemundo.com.do/set-4-bodys-manga-larga-7396384.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/7/3/7396384.jpg',
    category: 'Ropa',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    size: '3 o 6 meses',
  },
  {
    id: 'enterizo-flores-carters',
    name: "Enterizo Flores Carter's",
    description: 'Set de 4 enterizos de flores.',
    link: 'https://bebemundo.com.do/enterizo-flores-carter-s-7379895.html',
    imageUrl: 'https://bebemundo.com.do/media/catalog/product/cache/3a4e94d4d2f7d3f7e1c6b8e7d4e3f0a1/7/3/7379895.jpg',
    category: 'Ropa',
    store: 'bebemundo',
    totalQuantity: 1,
    availableQuantity: 1,
    size: '3 o 6 meses',
  },

  // --- Amazon Registry (extraídos del registry de Gabriela) -----------------
  {
    id: 'amzn-B0GL6Q52WR',
    name: 'Tapete de Juego Extragrande Reversible para Bebé',
    description: 'Tapete plegable de espuma 79x71 pulgadas, antideslizante.',
    link: 'https://www.amazon.com/dp/B0GL6Q52WR',
    imageUrl: 'https://m.media-amazon.com/images/I/51wu8psWVXL.jpg',
    category: 'Mobiliario',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B07V2XN3M4',
    name: 'Gorrito Conejito de Algodón Recién Nacida',
    description: 'Cute Rabbit Infant Beanie.',
    link: 'https://www.amazon.com/dp/B07V2XN3M4',
    imageUrl: 'https://m.media-amazon.com/images/I/31EGUTWvQyL.jpg',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0BL8N5RFB',
    name: "Simple Joys Carter's · Mamelucos Manga Corta x6",
    description: 'Paquete de 6 mamelucos para bebé niña.',
    link: 'https://www.amazon.com/dp/B0BL8N5RFB',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0BZVK52BK',
    name: 'Kiddiezoom · Canastilla 9 Piezas Unisex',
    description: 'Conjunto de mamelucos y pantalones, regalo unisex.',
    link: 'https://www.amazon.com/dp/B0BZVK52BK',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DNSMQCJ9',
    name: 'Kavousa · Mameluco Manga Larga con Diadema',
    description: 'Ropa para bebé niña recién nacida.',
    link: 'https://www.amazon.com/dp/B0DNSMQCJ9',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DTHB6PGQ',
    name: 'Younger Tree · Mono Verano con Diadema',
    description: 'Mono sin mangas para bebé niña.',
    link: 'https://www.amazon.com/dp/B0DTHB6PGQ',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0CKSZH9PV',
    name: 'Calcetines de Algodón con Volantes (6 o 12 pares)',
    description: 'Calcetines con puño doblado para bebé.',
    link: 'https://www.amazon.com/dp/B0CKSZH9PV',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B07GG1ZG7W',
    name: 'Gerber · Body Manga Larga Pack',
    description: 'Paquete de 3 o 6 bodys manga larga.',
    link: 'https://www.amazon.com/dp/B07GG1ZG7W',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B07GG8SRGL',
    name: 'Gerber · Mamelucos Manga Corta x8 Unisex',
    description: 'Paquete de 8 bodys unisex.',
    link: 'https://www.amazon.com/dp/B07GG8SRGL',
    imageUrl: '',
    category: 'Ropa',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0FPCNTK1J',
    name: 'Yoofoss · Toallas con Capucha Muselina Orgánica x2',
    description: '100% algodón orgánico, 37.5"x37.5".',
    link: 'https://www.amazon.com/dp/B0FPCNTK1J',
    imageUrl: 'https://m.media-amazon.com/images/I/41dniiZyBAL.jpg',
    category: 'Baño',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0FDQYCJCL',
    name: 'Bañera Plegable de Viaje con Termómetro',
    description: 'Bañera portátil grande con cojín, 0 a 36 meses.',
    link: 'https://www.amazon.com/dp/B0FDQYCJCL',
    imageUrl: 'https://m.media-amazon.com/images/I/41WhD-WK75L.jpg',
    category: 'Baño',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B08QY3N85N',
    name: 'Pampers Swaddlers Talla 2 · 186 unidades',
    description: 'Pañales 4.5-10 kg, absorbentes y seguros para la piel.',
    link: 'https://www.amazon.com/dp/B08QY3N85N',
    imageUrl: 'https://m.media-amazon.com/images/I/51ZTORCdf+L.jpg',
    category: 'Pañales',
    store: 'amazon',
    totalQuantity: 4,
    availableQuantity: 4,
  },
  {
    id: 'amzn-B0GPFKC532',
    name: 'Huggies Simply Clean · Toallitas 704 uds',
    description: 'Toallitas sin perfume, paquete de 22 abatibles.',
    link: 'https://www.amazon.com/dp/B0GPFKC532',
    imageUrl: 'https://m.media-amazon.com/images/I/51E+xOHyXlL.jpg',
    category: 'Higiene',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DJWSPZJ4',
    name: 'Huggies Snug & Dry Talla 5 · 168 uds',
    description: 'Pañales 27+ libras, 6 paquetes de 28.',
    link: 'https://www.amazon.com/dp/B0DJWSPZJ4',
    imageUrl: 'https://m.media-amazon.com/images/I/51jlCjwD0HL.jpg',
    category: 'Pañales',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DJWRGRM3',
    name: 'Huggies Snug & Dry Talla 4 · 186 uds',
    description: 'Pañales 22-37 libras, 6 paquetes de 31.',
    link: 'https://www.amazon.com/dp/B0DJWRGRM3',
    imageUrl: 'https://m.media-amazon.com/images/I/51otbbaqmVL.jpg',
    category: 'Pañales',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0G43JKTC5',
    name: 'Carrito Organizador de Pañales 3 Niveles',
    description: 'Con ruedas, divisores y 6 bolsillos de malla.',
    link: 'https://www.amazon.com/dp/B0G43JKTC5',
    imageUrl: 'https://m.media-amazon.com/images/I/41gAgWkvdpL.jpg',
    category: 'Organización',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B07Q7SWLB2',
    name: 'Aquaphor Baby · Set Cuidado de Piel 2 piezas',
    description: 'Ungüento curativo 14oz + crema contra sarpullido 3.5oz.',
    link: 'https://www.amazon.com/dp/B07Q7SWLB2',
    imageUrl: 'https://m.media-amazon.com/images/I/41B7aoWTCeL.jpg',
    category: 'Cuidado',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B00BH0PZBG',
    name: 'Desitin Crema Dermatitis Máxima Fortaleza',
    description: 'Crema púrpura para sarpullido del pañal.',
    link: 'https://www.amazon.com/dp/B00BH0PZBG',
    imageUrl: 'https://m.media-amazon.com/images/I/41wRc-Ep3rL.jpg',
    category: 'Cuidado',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0GMKC1VVD',
    name: "Dr. Brown's · Set Regalo Biberón Anti-Cólicos Rosa",
    description: 'Botella, sorbete, chupetes HappyPaci, tapas y cepillo.',
    link: 'https://www.amazon.com/dp/B0GMKC1VVD',
    imageUrl: 'https://m.media-amazon.com/images/I/41jqKFf8XTL.jpg',
    category: 'Alimentación',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0964G3WXC',
    name: 'Philips Avent · Biberón Natural Rosa 4oz x4',
    description: 'Pack de 4 biberones naturales con boquilla suave.',
    link: 'https://www.amazon.com/dp/B0964G3WXC',
    imageUrl: 'https://m.media-amazon.com/images/I/41dEU9iLQvL.jpg',
    category: 'Alimentación',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DKHCWJ5G',
    name: 'Momcozy · Calentador de Leche Portátil',
    description: 'Calentador para leche materna y agua, batería duradera.',
    link: 'https://www.amazon.com/dp/B0DKHCWJ5G',
    imageUrl: 'https://m.media-amazon.com/images/I/41b8g6Y7jGL.jpg',
    category: 'Alimentación',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DSN5WWFX',
    name: 'Honey Joy · Silla Alta 5 en 1 Convertible',
    description: 'Silla de alimentación con bandeja y arnés de seguridad.',
    link: 'https://www.amazon.com/dp/B0DSN5WWFX',
    imageUrl: 'https://m.media-amazon.com/images/I/41tJz3GqSuL.jpg',
    category: 'Mobiliario',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DM58DYGR',
    name: 'Konssy · Baberos Muselina con Volantes x3',
    description: '100% algodón, 0-36 meses.',
    link: 'https://www.amazon.com/dp/B0DM58DYGR',
    imageUrl: 'https://m.media-amazon.com/images/I/410zQOw1hQL.jpg',
    category: 'Alimentación',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0C6KNHFP3',
    name: 'Unnivoll · Paños de Eructos Muselina x12 Rosa',
    description: '100% algodón, extra suaves y absorbentes.',
    link: 'https://www.amazon.com/dp/B0C6KNHFP3',
    imageUrl: 'https://m.media-amazon.com/images/I/51tQz8GzR1L.jpg',
    category: 'Alimentación',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B09YTMPL4R',
    name: 'Kit de Manos y Huellas sin Tinta · Recuerdo',
    description: 'Almohadilla limpia, kit recuerdo para recién nacido.',
    link: 'https://www.amazon.com/dp/B09YTMPL4R',
    imageUrl: 'https://m.media-amazon.com/images/I/41IuvHc1QEL.jpg',
    category: 'Recuerdo',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0DDTZGLSG',
    name: 'Dove Baby · Set Hipoalergénico Loción + Gel 13oz',
    description: 'Pack de cuidado para piel sensible, sin fragancia.',
    link: 'https://www.amazon.com/dp/B0DDTZGLSG',
    imageUrl: 'https://m.media-amazon.com/images/I/31tYwxF23mL.jpg',
    category: 'Cuidado',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B07DGKXBD7',
    name: "Johnson's Baby · Loción Coco + Aloe Vera",
    description: 'Hidratación 72 horas, hipoalergénica.',
    link: 'https://www.amazon.com/dp/B07DGKXBD7',
    imageUrl: 'https://m.media-amazon.com/images/I/31jc9Bl6IuL.jpg',
    category: 'Cuidado',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0CDPZ5SXZ',
    name: 'KeaBabies · Sábanas Orgánicas Prado x2',
    description: 'Set de 2 sábanas 52x28, algodón jersey transpirable.',
    link: 'https://www.amazon.com/dp/B0CDPZ5SXZ',
    imageUrl: 'https://m.media-amazon.com/images/I/41MMevg5RzL.jpg',
    category: 'Mobiliario',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0CZXJWZ4M',
    name: 'KeaBabies · Sábanas Orgánicas Cameo x2',
    description: 'Set de 2 sábanas 52x28, algodón jersey transpirable.',
    link: 'https://www.amazon.com/dp/B0CZXJWZ4M',
    imageUrl: 'https://m.media-amazon.com/images/I/31clOAvufKL.jpg',
    category: 'Mobiliario',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
  {
    id: 'amzn-B0C7VM6R3N',
    name: 'GLLQUEN · Mantas de Recepción Muselina',
    description: 'Mantas suaves transpirables para envolver al recién nacido.',
    link: 'https://www.amazon.com/dp/B0C7VM6R3N',
    imageUrl: 'https://m.media-amazon.com/images/I/41Euy5bVhgL.jpg',
    category: 'Mobiliario',
    store: 'amazon',
    totalQuantity: 1,
    availableQuantity: 1,
  },
];
